//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using Project.Models;

    public partial class Help
    {
        [Required(ErrorMessage ="Required")]
        [Display(Name="User ID")]
        
        public Nullable<int> UserId { get; set; }
  
        [Display(Name = "Request ID")]
       
        public int RequestId { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Issue")]
        public string ISSUE { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Ticket Date")]
        public Nullable<System.DateTime> DateOfTicket { get; set; }
        public string Resolution { get; set; }
        public string Solved { get; set; }
    }
}
