//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ScholarshipRequest
    {
        [Display(Name = "Request ID")]
        public int Requestid { get; set; }
        [Display(Name ="Student ID")]
        public int StudentId { get; set; }
        [Display(Name = "Student Name")]
        public string StudentName { get; set; }
        [Display(Name = "Institution ID")]
        public int institutionId { get; set; }
        [Display(Name = "Institution Name")]
        public string institutionName { get; set; }
        [Display(Name = "Scholarship ID")]
        public int ScholarshipID { get; set; }
        [Display(Name = "Scholarship Name")]
        public string ScholarshipName { get; set; }
        [Display(Name = "Course")]
        public string Course { get; set; }
        [Display(Name = "Date of Approval")]
        public System.DateTime DateofApproval { get; set; }
        [Display(Name = "Score")]
        public int Score { get; set; }
        [Display(Name = "Annual Income")]
        public int AnnualIncome { get; set; }
        [Display(Name = "Approved ?")]
        public string ApprovedByInstitution { get; set; }
        [Display(Name = " Scholarship Amount")]
        public int ScholarshipAmount { get; set; }
    }
}
